name: CI Nexus Legacy (Git Flow)

on:
  pull_request:
    branches:
      - main
      - develop
      - 'release/**'

jobs:
  auditoria-e-testes:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Executando testes rigorosos e auditoria de segurança..."
